name: Build & Deploy Jekyll site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write       # allow publishing to GitHub Pages
  id-token: write    # needed by deploy-pages@v1

jobs:
  build:
    name: Build site
    runs-on: ubuntu-24.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Ruby & install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build \
            --source . \
            --destination _site

      - name: Inspect generated CSS
        run: head -n 20 _site/assets/css/main.css || true

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
          artifact_name: pages

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - name: Deploy Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: pages
