name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [ gh-pages ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2    # ← switch from 3.1.6 to 3.2.x
          cache: bundler

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install JS deps & build Tailwind
        run: |
          npm ci
          npm run build:css

      - name: Build Jekyll site
        run: bundle exec jekyll build --destination _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
