name: Build & Deploy to GitHub Pages

# 1) Run on each push to your source branch (main), not on gh-pages.
on:
  push:
    branches:
      - main

# 2) Grant the Pages API scope so peaceiris can push.
permissions:
  contents: read       # you need to checkout code
  pages: write         # allow gh-pages deploy
  id-token: write      # required by some Actions for OIDC auth

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install JS dependencies
        run: npm ci

      - name: Build Tailwind CSS
        run: npx @tailwindcss/cli -i ./assets/css/main.css -o ./_site/assets/css/main.css --minify

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: bundler

      - name: Install Ruby gems
        run: bundle install --jobs 4 --retry 3

      - name: Build Jekyll site
        run: bundle exec jekyll build --destination _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages